services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: apobasi_backend
    env_file: .env
    volumes:
      - backend_static:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - apobasi_net
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 apo_basi.asgi:application"

  postgres:
    image: postgres:15-alpine
    container_name: apobasi_postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apobasi_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: apobasi_redis
    env_file: .env
    volumes:
      - redis_data:/data
    networks:
      - apobasi_net
    restart: unless-stopped

networks:
  apobasi_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  backend_static: